qa-openrc: drop user:group check
root is not necessarily what's expected, e.g. gives QA on prefix
(could ignore prefix, but there could be other obscure situations).

test would also be broken if ran as root (for some reason) given
it'd give the expected value and would require a UID check, now can
just check that no QA was emitted with -!

diff --git a/scripts/qa-openrc b/scripts/qa-openrc
--- a/scripts/qa-openrc
+++ b/scripts/qa-openrc
@@ -110,8 +110,8 @@ export -f openrc-echo_if_service
 #	be useful if init scripts are installed by upstream build system.
 openrc-check_permissions() {
 	local permissions
-	local expected_value="-rwxr-xr-x root:root"
-	permissions=$(stat -c'%A %U:%G' "${1}" || die "stat failed")
+	local expected_value=-rwxr-xr-x
+	permissions=$(stat -c%A "${1}") || die "stat failed"
 	if [[ ${permissions} != "${expected_value}" ]]; then
 		msg "OPENRC: incorrect permissions for service '$(basename "${1}")'"
 		msg "    have: ${permissions}"
