scripts: fix small nitpicks

diff --git a/scripts/qa-sed b/scripts/qa-sed
--- a/scripts/qa-sed
+++ b/scripts/qa-sed
@@ -62,10 +62,10 @@ sed-run_exit() { sed-run; exit $(sed-get_errno ${?}); }
 die() { echo "Error (${0##*/}): ${*}" >&2; sed-run_exit; }
 
 # Dependencies:
-#	sys-apps/coreutils (readlink)
+#	sys-apps/coreutils (cat,readlink)
 #	sys-apps/sed (sed)
 #	sys-apps/util-linux (getopt)
-type getopt readlink sed >/dev/null || die "missing dependencies"
+type cat getopt readlink sed >/dev/null || die "missing dependencies"
 
 declare -A OPT
 OPT[all]=false
@@ -120,7 +120,7 @@ sed-qa() {
 		local IFS= line
 		local -i c=0
 		while read -r line; do
-			(( ++c < ${OPT[lineno]} )) && continue
+			(( ++c < OPT[lineno] )) && continue
 
 			echo "${line}" >&2
 
@@ -141,8 +141,7 @@ sed-qa() {
 # check for known GNU sed options with arguments to recognize it as not
 # being a file. This is not explicitely necessary due to the read test
 # (see below), but is an added safety (notably for --file).
-eval opts=(
-	$(getopt -q \
+opts=(eval $(getopt -q \
 		-o hie:f:l: \
 		-l help,version,in-place,expression:,file:,line-length: \
 		-- "${SED_ARGV[@]}"))
diff --git a/scripts/qa-vdb b/scripts/qa-vdb
--- a/scripts/qa-vdb
+++ b/scripts/qa-vdb
@@ -61,13 +61,13 @@ trap 'exit 1' USR1
 
 # Dependencies:
 #	app-portage/portage-utils (qatom,qfile,qlist)
-#	sys-apps/coreutils (sort,tr,uniq)
+#	sys-apps/coreutils (cat,sort,tr,uniq)
 #	sys-apps/diffutils (diff)
 #	sys-apps/portage (portageq)
 #	sys-apps/sed (sed)
 #	sys-apps/util-linux (getopt)
 #	sys-libs/glibc (ldconfig) [optional]
-type diff getopt portageq qatom qfile qlist sed sort tr uniq >/dev/null || die "missing dependencies"
+type cat diff getopt portageq qatom qfile qlist sed sort tr uniq >/dev/null || die "missing dependencies"
 
 declare -A OPT
 OPT[slot]=true
@@ -330,11 +330,11 @@ vdb-get_deps() {
 		# Handle ( ) and || ( ) deps loosely (allow missing deps within a group)
 		[[ ${rdep} == '||' ]] && continue
 		if [[ ${rdep} == '(' ]]; then
-			let group++
+			(( group++ ))
 			continue
 		fi
 		if [[ ${rdep} == ')' ]]; then
-			let group--
+			(( group-- ))
 			continue
 		fi
 
@@ -509,7 +509,7 @@ vdb-set_exclude() {
 vdb-set_ldcache() {
 	local ldconfig IFS=$'\n'
 	ldconfig=($(type -P ldconfig /sbin/ldconfig /usr/sbin/ldconfig 2>/dev/null))
-	if [[ ! ${ldconfig} ]]; then
+	if [[ ${#ldconfig[@]} == 0 ]]; then
 		LDCACHE=
 		return
 	fi
