qa-vdb: add support for pkg=dep exclusions
Intended for if frequently work with a package and want to
disable a specific notice without disabling for every package nor
constantly passing command line options for it.

diff --git a/scripts/qa-vdb b/scripts/qa-vdb
--- a/scripts/qa-vdb
+++ b/scripts/qa-vdb
@@ -74,7 +74,7 @@ OPT[slot]=true
 OPT[bind]=true
 OPT[overbind]=true
 OPT[extra]=true
-OPT[exclude]=
+OPT[exclude-all]=
 OPT[exclude-slot]=
 OPT[exclude-bind]=
 OPT[exclude-extra]=
@@ -99,7 +99,7 @@ while [[ ${#} != 0 ]]; do
 		-b|--no-bind) OPT[bind]=false;;
 		-o|--no-overbind) OPT[overbind]=false;;
 		-x|--no-extra) OPT[extra]=false;;
-		-e|--exclude) OPT[exclude]+=,${2}; shift;;
+		-e|--exclude) OPT[exclude-all]+=,${2}; shift;;
 		   --exclude-slot) OPT[exclude-slot]+=,${2}; shift;;
 		   --exclude-bind) OPT[exclude-bind]+=,${2}; shift;;
 		   --exclude-extra) OPT[exclude-extra]+=,${2}; shift;;
@@ -119,6 +119,12 @@ done
 #	Echos <atom> based on <format> using qatom -F.
 vdb-get_atomf() {
 	qatom -CqF "${@}" || die "q command failed: qatom -CqF ${*}"
+}
+
+# vdb-get_pf2pn <CATEGORY/PF>
+#	Echos CATEGORY/PN after removing version from PF, wrapper to vdb-get_atomf
+vdb-get_pf2pn() {
+	vdb-get_atomf '%{CATEGORY}/%{PN}' "${1}"
 }
 
 # vdb-get_dep2entry <dependency>
@@ -163,7 +169,7 @@ vdb-get_entry() {
 	echo ${match}
 }
 
-# vdb-get_expected_slot <CATEGORY/PN> <SLOT> <SUBSLOT> [prebuilt]
+# vdb-get_expected_slot <CATEGORY/PN(dep)> <SLOT> <SUBSLOT> <CATEGORY/PN(pkg)> [prebuilt]
 #	Echos :SLOT= string that'd be expected in dependencies.
 #	- if slot is non-zero, should have a :N
 #	- if subslot is non-zero, should (usually) have :=
@@ -174,10 +180,10 @@ vdb-get_entry() {
 vdb-get_expected_slot() {
 	local slot=${2} subslot=${3}
 
-	if ! ${OPT[slot]} || vdb-is_excluded_slot ${1}; then
+	if ! ${OPT[slot]} || vdb-is_excluded slot ${1} ${4}; then
 		 slot=0
 	fi
-	if ! ${OPT[bind]} || vdb-is_excluded_bind ${1} || [[ ${4:-} == prebuilt ]]; then
+	if ! ${OPT[bind]} || vdb-is_excluded bind ${1} ${4} || [[ ${5:-} == prebuilt ]]; then
 		subslot=0
 	fi
 
@@ -199,13 +205,15 @@ vdb-get_libdeps() {
 	local prebuilt=
 	vdb-is_prebuilt ${1} && prebuilt=prebuilt
 
+	local pkg=$(vdb-get_pf2pn ${1})
+
 	local IFS=$'\n' provides rdep vrdep
-	for rdep in $(vdb-get_deps "${1}"); do
+	for rdep in $(vdb-get_deps ${1}); do
 		IFS=' '
 		rdep=(${rdep})
 
 		# check if requested for exclusion through --exclude
-		vdb-is_excluded ${rdep[1]} && continue
+		vdb-is_excluded all ${rdep[1]} ${pkg} && continue
 
 		# need to skip entries that do not provide shared libraries but,
 		# to know this, need to check what virtuals resolve to
@@ -229,11 +237,11 @@ vdb-get_libdeps() {
 		fi
 
 		# if --no-extra, exclude if not found in vdb-get_libneed's output
-		if ! ${OPT[extra]} || vdb-is_excluded_extra ${rdep[1]}; then
+		if ! ${OPT[extra]} || vdb-is_excluded extra ${rdep[1]} ${pkg}; then
 			[[ ${need} == *${rdep[1]}* ]] || continue
 		fi
 
-		echo "${rdep[1]}$(vdb-get_expected_slot ${rdep[1]} ${rdep[2]} ${rdep[3]} ${prebuilt})"
+		echo "${rdep[1]}$(vdb-get_expected_slot ${rdep[1]} ${rdep[2]} ${rdep[3]} ${pkg} ${prebuilt})"
 	done
 }
 
@@ -256,6 +264,8 @@ _vdb-get_libneed() {
 	local prebuilt=
 	vdb-is_prebuilt ${1} && prebuilt=prebuilt
 
+	local pkg=$(vdb-get_pf2pn ${1})
+
 	# read REQUIRES with stripped 'x86_64: ' and then use qfile to
 	# find the matching installed package
 	local IFS dep entry slot subslot virtual
@@ -263,8 +273,7 @@ _vdb-get_libneed() {
 		sed 's/[^ ]*: //g' < "${VDB}"/${1}/REQUIRES | \
 		xargs qfile -CqvP | sort | uniq \
 		|| die "failed to get dependencies from REQUIRES for '${1}'"); do
-		# use qatom to (hopefully safely) trim versions
-		dep=$(vdb-get_atomf '%{CATEGORY}/%{PN}' "${entry}")
+		dep=$(vdb-get_pf2pn "${entry}")
 
 		# check rdepend for virtuals and the the virtual's rdepend for this dep
 		IFS=$'\n'
@@ -282,7 +291,7 @@ _vdb-get_libneed() {
 		done
 
 		# with final cat/pn, check if requested for exclusion through --exclude
-		vdb-is_excluded ${dep} && continue
+		vdb-is_excluded all ${dep} ${pkg} && continue
 
 		# get SLOT information
 		slot=0; subslot=0
@@ -294,7 +303,7 @@ _vdb-get_libneed() {
 			fi
 		fi
 
-		echo "${dep}$(vdb-get_expected_slot ${dep} ${slot} ${subslot} ${prebuilt})"
+		echo "${dep}$(vdb-get_expected_slot ${dep} ${slot} ${subslot} ${pkg} ${prebuilt})"
 	done | sort | uniq
 }
 
@@ -388,37 +397,15 @@ vdb-get_subslot() {
 	echo 0
 }
 
-# vdb-is_excluded <CATEGORY/PN>
-#	Return true if should be excluded based on --exclude
+# vdb-is_excluded <all|slot|bind|extra> <CATEGORY/PN(dep)> <CATEGORY/PN(pkg)>
+#	Return true if dep shouldn't be considered when checking pkg
+#	Types are based on --exclude* options
 vdb-is_excluded() {
-	[[ ${OPT[exclude]} ]] || return 1
+	[[ ${OPT[exclude-${1}]} ]] || return 1
 
-	eval "[[ \${1%:*} =~ ^(${OPT[exclude]})$ ]]"
-}
-
-# vdb-is_excluded_extra <CATEGORY/PN>
-#	Return true if should ignore unspecified slots
-vdb-is_excluded_slot() {
-	[[ ${OPT[exclude-slot]} ]] || return 1
-
-	eval "[[ \${1%:*} =~ ^(${OPT[exclude-slot]})$ ]]"
-}
-
-
-# vdb-is_excluded_bind <CATEGORY/PN>
-#	Return true if should exclude binding operators based on --exclude-bind
-vdb-is_excluded_bind() {
-	[[ ${OPT[exclude-bind]} ]] || return 1
-
-	eval "[[ \${1%:*} =~ ^(${OPT[exclude-bind]})$ ]]"
-}
-
-# vdb-is_excluded_extra <CATEGORY/PN>
-#	Return true if should assume dep is needed even if no shared libs used.
-vdb-is_excluded_extra() {
-	[[ ${OPT[exclude-extra]} ]] || return 1
-
-	eval "[[ \${1%:*} =~ ^(${OPT[exclude-extra]})$ ]]"
+	# strip = prefixes if matches package to activate them
+	# eval is needed to enable globs
+	eval "[[ \${2%:*} =~ ^(${OPT[exclude-${1}]//${3}=/})$ ]]"
 }
 
 # vdb-is_prebuilt <CATEGORY/PF>
@@ -481,27 +468,30 @@ vdb-print_libdiff() {
 # vdb-set_exclude <exclude*>
 #   Load exclude configs and prepare supplied ${OPT[exclude*]} for use
 vdb-set_exclude() {
-    local -a conf=()
 	if ${OPT[default-exclude]}; then
+    	local -a conf=()
+		local file=qa-vdb.exclude-${1}
+		file=${file%-all}
+
 		if [[ ${OPT[confdir]} ]]; then
-			[[ -r ${OPT[confdir]}/qa-vdb.${1} ]] && conf=("${OPT[confdir]}/qa-vdb.${1}")
+			[[ -r ${OPT[confdir]}/${file} ]] && conf=("${OPT[confdir]}/${file}")
 		else
-			[[ -r ${OPT[sysconfdir]}/qa-vdb.${1} ]] && conf=("${OPT[sysconfdir]}/qa-vdb.${1}")
-			[[ -r ${OPT[userconfdir]}/qa-vdb.${1} ]] && conf+=("${OPT[userconfdir]}/qa-vdb.${1}")
+			[[ -r ${OPT[sysconfdir]}/${file} ]] && conf=("${OPT[sysconfdir]}/${file}")
+			[[ -r ${OPT[userconfdir]}/${file} ]] && conf+=("${OPT[userconfdir]}/${file}")
 		fi
 
 		if [[ ${conf[*]} ]]; then
-			OPT[${1}]+=,$(sed 's/#.*//' "${conf[@]}" | tr '\r\n' ',,' \
+			OPT[exclude-${1}]+=,$(sed 's/#.*//' "${conf[@]}" | tr '\r\n' ',,' \
 				|| die "failed reading configuration files")
 		fi
 	fi
 
 	# create a simple a|b|c, escape +, and * -> .*
-	OPT[${1}]=$(sed \
-		-e 's/[^A-Za-z0-9_/+*,-]//g' \
+	OPT[exclude-${1}]=$(sed \
+		-e 's/[^A-Za-z0-9_/+*,=-]//g' \
 		-e 's/,,*/|/g;s/^|//;s/|$//' \
 		-e 's/+/\\+/g;s/\*/.*/g' \
-		<<< "${OPT[${1}]}") || die "sed failed"
+		<<< "${OPT[exclude-${1}]}") || die "sed failed"
 }
 
 # vdb-set_ldcache
@@ -533,10 +523,10 @@ vdb-set_vdb() {
 vdb-init() {
 	vdb-set_vdb
 	vdb-set_ldcache
-	vdb-set_exclude exclude
-	vdb-set_exclude exclude-slot
-	vdb-set_exclude exclude-bind
-	vdb-set_exclude exclude-extra
+	vdb-set_exclude all
+	vdb-set_exclude slot
+	vdb-set_exclude bind
+	vdb-set_exclude extra
 }
 
 vdb-init
